apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend           # Matches the "app: backend" label in the Deployment
  ports:
    - protocol: TCP
      port: 5000           # Port that the Service will expose
      targetPort: 5000      # Port on the Pod where the backend container is listening
  type: ClusterIP          # Use NodePort or LoadBalancer if external access is needed
