apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: eldadmwangi/kubernetes-backend
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"  # Minimum memory required
            cpu: "250m"      # Minimum CPU required
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "500m"      # Maximum CPU allowed
